CREATE TABLE EMPLOYEE(
	SSN INT(10) PRIMARY KEY ,
	NAME CHAR(100) NOT NULL ,
	LOT INT(100) UNIQUE KEY ,
);
CREATE TABLE DEPT(
	DID INT(10) PRIMARY KEY,
	DNAME CHAR(100),
	BUDGET INT,
);
CREATE TABLE WORK_IN(
	SSN INT(10),
	DID CHAR(100),
	SINCE CHAR(100),
	PRIMARY(SSN,DID),
	CONSTRAINT SACHIN1 
	FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
	ON DELETE CASCADE , 
	CONSTRAINT SACHIN2
	FOREIGN KEY (DID) REFERENCES DEPT (DID) 
	ON DELETE CASCADE
);